# Site settings
title: hadileonard.
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hadileonard
user_description: This website's purpose is for me to fully implement a CI/CD pipeline utilizing AWS. After recently earning my GCP Associate Cloud Engineer certification from Google, I decided to build a simple website that employs a full CI/CD pipeline, with a little twist, I will do it on AWS.
user_title: Software Developer
email: hadileonardd@gmail.com
twitter_username: panhellenics
linkedin_username: https://www.linkedin.com/in/hadianto-leonard
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum
blog_link: https://google.com

exclude: ['package.json', 'src', 'node_modules', 'vendor']

